# Generated by Django 3.2.5 on 2021-07-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='zipcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
