# Generated by Django 3.2.5 on 2021-07-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210724_0748'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_last_na_e6a359_idx',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='given_name',
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'given_name'], name='store_custo_last_na_311049_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
